# Generated by Django 5.2.6 on 2025-12-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='User bio/description', max_length=500, null=True),
        ),
    ]
